INSERT INTO themes (name, slug) VALUES
 ('Personal finance & investing','finance'),
 ('Coding & programming','coding'),
 ('Data analysis & spreadsheets','data-analysis'),
 ('Data science & machine learning','data-science'),
 ('DSA & technical interview prep','dsa-interview'),
 ('Interview prep (non-technical)','interview-prep'),
 ('Career skills','career-skills'),
 ('Project management','project-management'),
 ('Sales skills','sales'),
 ('Marketing & copywriting','marketing'),
 ('Leadership & people management','leadership'),
 ('Negotiation & persuasion','negotiation'),
 ('Public speaking & communication','public-speaking'),
 ('Entrepreneurship & side hustles','entrepreneurship'),
 ('Logical reasoning & aptitude','logical-reasoning'),
 ('Cybersecurity & digital privacy','cybersecurity'),
 ('Writing & storytelling','writing'),
 ('Design (UI/UX & graphic)','design'),
 ('Photography & videography','photography'),
 ('Video & photo editing','editing'),
 ('Drawing & digital art','drawing'),
 ('3D modeling & animation','3d-animation'),
 ('Music theory & instrument basics','music'),
 ('Woodworking & maker skills','woodworking'),
 ('Content creation & audience growth','content-creation'),
 ('Sketching & calligraphy','sketching-calligraphy'),
 ('Productivity & time management','productivity'),
 ('Mental models & critical thinking','critical-thinking'),
 ('Habit building & behavior change','habits'),
 ('Learning how to learn','learning'),
 ('Speed reading & note-taking','note-taking'),
 ('Emotional intelligence & conflict resolution','emotional-intelligence'),
 ('Meditation, mindfulness & stress management','mindfulness'),
 ('Social skills & relationship building','social-skills'),
 ('Language learning','language-learning'),
 ('Grooming & styling','grooming-styling'),
 ('Cooking technique','cooking'),
 ('Strength training & fitness form','fitness'),
 ('Home & appliance repair','home-repair'),
 ('Gardening & plant care','gardening'),
 ('Car maintenance & mechanics','car-maintenance'),
 ('Chess & strategy','chess')
ON CONFLICT (slug) DO NOTHING;
